### ISSUE TITLE
I needs to be STR$(I) in TeleBASIC

### ISSUE THREAD

**Issue by mobluse** [telehack-foundation/.github#1]
In basic.md you have this example that doesn't work in most terminals:
```
10  FOR I = 0 TO 255
20  S$ = TH_SPRINTF$( "%4S", I )
30  ? CHR$(27) "[38;5;" I "m" S$ ;
40  IF NOT (I+1) MOD 16 THEN ?
50  NEXT
```
One has to change line 30 in TeleBASIC to
`30  ? CHR$(27) "[38;5;" STR$(I) "m" S$ ;`
since just `I` inserts a space before the number and that makes the escape code not work.

You might alternatively change TeleBASIC so that `I` is converted to string without space before the number for positive numbers. In GW-BASIC and MBASIC STR$(I) inserts a space before positive numbers, but I don't think TeleBASIC has to follow this. MID$() also works differently in TeleBASIC and GWBASIC/MBASIC, but there I think the GWBASIC/MBASIC behavior is better. I made an MBASIC version:

```
5 WIDTH 255
10 FOR I = 0 TO 255
20 S$ = MID$(STR$(I),2)
30 PRINT CHR$(27) "[38;5;" S$ "m" ;
35 PRINT USING "\  \";S$ ;
40 IF 0 = ((I+1) MOD 16) THEN PRINT
50 NEXT
```

**Comment by thunderpoot** [comment]
Thanks @mobluse, that typo has been corrected
