### ISSUE TITLE
Problem with BCD in c8 Chip-8 interpreter

### ISSUE THREAD

**Issue by agwells** [telehack-foundation/.github#3]
Hi!

I'm new to Chip-8, but I've noticed that the BCD command (`Fx33`) in Telehack's `c8` seems to behave incorrectly.

[From what I've read](https://chip8.gulrak.net/#fx33), it's supposed to store the digit for the hundreds place at `i`, the tens place at `i+1`, and the ones place at `i+2`. But, it actually skips any leading zeroes. So, if you convert a 2-digit number to BCD, it stores the tens place at `i` and the ones place at `i+1` (and the hundreds place nowhere). Likewise, a 1-digit number gets stored at `i`.

###  Replication instructions 

Run this program, and inspect the value of the registers afterward.
```chip8
6E01 A300 FE33
6E10 A303 FE33
6EFF A306 FE33
A300 F865
```

**Expected result:** Registers `v0` through `v8` show:

| v0 | v1 | v2 | v3 | v4 | v5 | v6 | v7 | v8 |
|-- |-- |-- |-- |-- |-- |-- |-- |-- |
| 0 | 0 | 1 | 0 | 1 | 6 | 2 | 5 | 5 |

**Actual result:** Registers `v0` through `v8` show:

| v0 | v1 | v2 | v3 | v4 | v5 | v6 | v7 | v8 |
|-- |-- |-- |-- |-- |-- |-- |-- |-- |
| 1 | 0 | 0 | 1 | 6 | 0 | 2 | 5 | 5 |

**Comment by thunderpoot** [comment]
Hi @agwells thanks for the report, we'll look into this.

**Comment by thunderpoot** [comment]
@telnet23 fished out some extra details:

> This document also describes the expected behavior even more explicitly:
> 
> Fx33 - LD B, Vx
> Store BCD representation of Vx in memory locations I, I+1, and I+2.
> 
> The interpreter takes the decimal value of Vx, and places the hundreds digit in memory at location in I, the tens digit at location I+1, and the ones digit at location I+2.
> 
> http://devernay.free.fr/hacks/chip8/C8TECH10.HTM#Fx33

Anyway, this should now be fixed, thanks again for the report, @agwells.

**Comment by agwells** [comment]
Yep, it works as expected now. Cheers for the quick turnaround!
